- gravityview.php
- includes/default-widgets.php
- readme.txt
It had a require call to the old file location
> Restored default-widgets to fix A-Z Entries Extension

- gravityview.php
- includes/widgets/class-gravityview-widget-page-links.php
- readme.txt
not working when search is placed.
Error created by improving security on add_query_arg
> Fixing Page links

- includes/extensions/edit-entry/class-edit-entry.php
New filter (returns boolean):
`gravityview/edit_entry/user_can_edit_entry`
Closes #346
> Added filter to check_user_cap_edit_entry

- includes/class-gravityview-extension.php
it completely crashes all the extensions!
> fix extensions conflict

- includes/class-api.php
- includes/fields/website.php
- readme.txt
- templates/fields/website.php
Enables Merge Tags as well.
Related to [HS
2405](https://secure.helpscout.net/conversation/90994293/2405/).
> Allow custom link text for Website fields

- includes/admin/metaboxes/views/gravityview-navigation.php
The tabs looked bad while loading
> Fix tabs style with JS disabled or while loading

- includes/class-change-entry-creator.php
- includes/class-common.php
- includes/widgets/search-widget/class-search-widget.php
- readme.txt
Added: Possibility to search by entry creator on Search Bar and Widget
> search by entry creator

- includes/class-image.php
from '%s="%s"' to ' %s="%s"' on line 178
+ WP Coding standards
> fixed spacing between attributes

- gravityview.php
- readme.txt
due to GFAddOn:get_app_setting
> min version required 1.8.7

- .gitattributes
- screenshots/index.php
Thanks,
http://blog.wppusher.com/everything-wordpress-developers-need-to-know-ab
out-gitattributes/
> Improve .zip generation

- includes/class-admin-approve-entries.php
> Prevent errors when not Approve/Disapprove

- assets/js/fe-views.js
- readme.txt
Fixes #361 - thanks @Idealien !
> Fix IE8 JS error

- gravityview.php
- includes/class-admin-welcome.php
- readme.txt
- templates/list-single.php
I'm getting a few users complaining about this on support.
@zackkatz after you merge this one, release a new point release.
> Fixing an fatal error when rendering list-single.php

- includes/extensions/delete-entry/class-delete-entry.php
- includes/extensions/edit-entry/partials/form-buttons.php
- readme.txt
@luistinygod Will this cause :rocket: ?
> Add CSS class to Edit Entry buttons

- includes/class-admin-approve-entries.php
A User reported that on latest version there was a Administration warning when Bulk Editing.
> Fixing Bulk Edit Warning

- includes/extensions/edit-entry/class-edit-entry-render.php
- readme.txt
Date and time fields where not being correctly populated when using field inputs.
> Fixed: edit date and time field 

- includes/class-gravityview-extension.php
- readme.txt
> Fixed: Extension translations

- includes/class-common.php
- includes/wordpress-widgets/class-gravityview-recent-entries-widget.php
- readme.txt
Fixed: Conflicts with Advanced Filter extension when using the Recent
Entries widget.
> Recent Entries widget

- includes/class-common.php
- readme.txt
allow extensions to inject new fields to be sorted.
> hook gravityview/common/sortable_fields

- includes/class-common.php
- readme.txt
> Check if cache returned anything

- includes/class-api.php
- includes/class-debug-bar.php
- includes/class-frontend-views.php
- includes/class-logging.php
> Improve Debug Bar output

- gravityview.php
- includes/class-frontend-views.php
- includes/class-gravityview-shortcode.php
- includes/class-template.php
- includes/widgets/class-gravityview-widget-pagination-info.php
Move the `[gravityview]` shortcode out of frontend class.
> Refactor shortcode

- includes/class-post-types.php
- readme.txt
> Add filter to make Views hierarchical

- assets/css/scss/admin-tooltips.scss
See https://github.com/katzwebservices/GravityView/issues/438
> Remove redundant jquery-ui close icon

- includes/class-gravityview-merge-tags.php
- tests/unit-tests/connector-API_Test.php
They weren't accessible before. Fixes #504
> Add support for `{user:roles}` and `{created_by:roles}`

- includes/widgets/search-widget/templates/search-field-link.php
> Fix links not using value as well as choice label

- includes/class-api.php
- includes/class-common.php
- includes/fields/list.php
- templates/fields/list.php
Use the `gravityview/fields/list/column-format` filter to display as
CSV instead of HTML.
> Add the ability to show a single value for a list field column

- includes/widgets/search-widget/class-search-widget.php
> Define default search bar to be "search everything"

- includes/class-gravityview-merge-tags.php
- tests/unit-tests/GravityView_Merge_Tags_Test.php
Accept URL parameters for Merge Tags.
> {get} Merge Tag

- assets/js/field-approval.js
moved attribute changes to update_approval and replaced gvApproval.label_approve with correct property names
> Fixed state change and sticky values

- includes/admin/metaboxes/class-gravityview-admin-metaboxes.php
- includes/class-admin-add-shortcode.php
- includes/class-admin-views.php
- includes/class-admin.php
- includes/class-data.php
- includes/class-debug-bar.php
@zackkatz requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/gravityview/GravityView/
> Scrutinizer Auto-Fixes

- includes/extensions/edit-entry/class-edit-entry-render.php
fix number fields that disappeared
> adding original form before save_lead

- includes/extensions/edit-entry/partials/form-buttons.php
- readme.txt
New filter `gravityview/edit_entry/button_labels`
> added filter gravityview/edit_entry/button_labels

- gravityview.php
- includes/class-admin-welcome.php
- includes/class-api.php
- readme.txt
> 1.16.4.1 hotfix

- includes/class-admin-welcome.php
> Bump the admin-welcome.php

- includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-flow.php
- includes/widgets/search-widget/class-search-widget.php
- includes/widgets/search-widget/templates/widget-search.php
Getting started. Currently a Work In Progress (`[WIP]`), not ready for merge.
> [WIP] Allow searching by Gravity Flow statuses and steps

- includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-survey.php
- readme.txt
> Add support for survey field in Search Bar

- gravityview.php
- includes/class-admin-welcome.php
- includes/class-admin.php
- languages/gravityview.pot
- readme.txt
The "form doesn't exist" error is bad enough to warrant a release.
> Version 1.19.1

- .travis.yml
- future/gravityview.php
- future/includes/class-gv-core.php
- future/includes/class-gv-plugin.php
- future/includes/index.php
- future/index.php
- gravityview.php
- includes/class-gravityview-compatibility.php
- tests/unit-tests/GravityView_Future_Test.php
We're moving towards a new API and refactoring the core components as we go. This will be an ever-rolling iterative cycle, where the new API is merged into the mainline (via develop) as to prevent large conflicts on mergesets, battletest the new APIs as they are used internally, and generally move fast and (hopefully not) break things.
Testing the water with this first pull and merge.
> The future begins now

- includes/class-gravityview-compatibility.php
- tests/unit-tests/GravityView_Future_Test.php
Bug exposed in bfde6b when checking same versions. Thanks, unit tests :)
> Fix version check in Compatibility class

- includes/class-data.php
- includes/class-oembed.php
- tests/unit-tests/GravityView_Future_Test.php
View attributes are not stored anywhere in this point of the commit history.
> Fix Issue #848

- future/_mocks.php
- future/includes/class-gv-collection-field.php
- future/includes/class-gv-collection-view.php
- future/includes/class-gv-entry.php
- future/includes/class-gv-form.php
- gravityview.php
- includes/class-admin-welcome.php
- includes/class-frontend-views.php
- includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-acf.php
- languages/gravityview.pot
- readme.txt
Small fixes but could be important for some customers.
> Version 1.21.2

- future/includes/class-gv-extension.php
> Extension class $is_compatible type fix

- includes/class-admin-views.php
Let gravityview/Joins handle this ;-)
> Strip out hard-coded joins HTML

- .travis.yml
- future/includes/class-gv-extension.php
- includes/class-admin-welcome.php
- languages/gravityview.pot
- readme.txt
This was quite the thing to find.
> Version 2.0.12 - Fix shiny updates

- future/includes/class-gv-collection-field.php
- future/includes/class-gv-template-entry-table.php
- future/lib/EDD_SL_Plugin_Updater.php
- gravityview.php
- includes/class-admin-views.php
- includes/class-admin-welcome.php
- includes/lib/EDD_SL_Plugin_Updater.php
- readme.txt
Hotfix to fix the Custom Content issue that wasn't fixed in 2.0.13.
> Version 2.0.13.1

- future/includes/class-gv-view.php
- tests/unit-tests/GravityView_Joins_Test.php
> Add filters for approved entries on joined Views

- future/includes/class-gv-settings-addon.php
[Issue](https://github.com/gravityview/Maps/issues/100) reported under Maps.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1119302972698439)
> Get GV options from the main site (blog) in multisite environment

- assets/js/fe-views.js
- readme.txt
Fixes #1346 (see discussion on why)
> Remove back link cookies

- includes/fields/class-gravityview-field-unsubscribe.php
- tests/unit-tests/GravityView_Field_Test.php
> Unsubscribe

- includes/widgets/search-widget/class-search-widget.php
- readme.txt
- tests/unit-tests/GravityView_Widget_Search_Test.php
@soulseekah Customer doesn't want to use CSS to include fields in search bar, then hide fields using CSS on front-end just to allow searching the fields
- What do you think about adding this filter?
- How about the filter name?
- If you are okay with it, can you write some tests for it and merge it?
Thanks!
> Add filter for searchable fields

- includes/extensions/delete-entry/class-delete-entry.php
- includes/extensions/edit-entry/class-edit-entry-locking.php
- includes/extensions/edit-entry/class-edit-entry-render.php
- includes/extensions/edit-entry/class-edit-entry.php
- templates/fields/field-edit_link-html.php
> Feature/edit locking [WIP]

- future/includes/class-gv-renderer-entry.php
- future/includes/class-gv-renderer-field.php
- future/includes/class-gv-renderer-view.php
- future/includes/class-gv-request.php
- future/includes/class-gv-wrappers.php
- includes/widgets/search-widget/class-search-widget.php
- readme.txt
- Allows new request types to use the renderers.
- Add `gravityview/widget/search/form/action` filter.
- Remove esc_url from search form URL. Sanitize early, escape late.
Work on https://github.com/gravityview/Admin-Views/issues/1
> Admin Views requisites

- includes/class-gravityview-entry-list.php
- includes/extensions/delete-entry/class-delete-entry.php
- includes/extensions/duplicate-entry/class-duplicate-entry.php
- includes/extensions/edit-entry/class-edit-entry-render.php
- includes/extensions/edit-entry/class-edit-entry.php
- readme.txt
- templates/fields/field-other_entries-html.php
> [WIP] Admin Views requisites (Part 2)

- includes/extensions/duplicate-entry/class-duplicate-entry.php
> [WIP] Admin Views requisites (Part 3)

- includes/admin/field-types/type_number.php
- includes/fields/class-gravityview-field-gravatar.php
- readme.txt
- templates/fields/field-gravatar-html.php
Who doesn't love globally-recognized avatars?
> Add Gravatar field

- includes/class-common.php
- includes/class-frontend-views.php
Fixes #1435 without introducing possible 🔒 gaps
> Fix (better) the single entry title not working

- includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravityformspartialentries.php
- readme.txt
> Do not try to save a partial entry without an ID

- future/includes/class-gv-settings-view.php
- future/includes/class-gv-view.php
- future/includes/rest/class-gv-rest-route.php
- future/includes/rest/class-gv-rest-views-route.php
- tests/unit-tests/GravityView_Future_Test.php
- tests/unit-tests/GravityView_REST_Test.php
The docs need to be updated, but since they're the same renderer other than the separator, it was easy to implement and closes a ticket!
Resolves #1474
> Allow exporting as TSV

- assets/js/fe-views.js
- readme.txt
Addresses scenarios described in [this video](https://gravityview.slack.com/archives/C727B06MB/p1625871546289400).
> Tweak search widget reset/clear button behavior

- includes/extensions/edit-entry/class-edit-entry-render.php
See #1629 for the issue description and test scenario.
> Handle unchanged multi-file upload field contents in Edit Entry

- future/includes/class-gv-shortcode-gventry.php
- includes/extensions/edit-entry/class-edit-entry-render.php
- includes/extensions/edit-entry/class-edit-entry.php
- readme.txt
- tests/unit-tests/GravityView_Edit_Entry_Test.php
This fixes #1390 and also #850.
> Fix Edit Entry link not working inside embedded Single Entry views

- future/includes/class-gv-shortcode-gvlogic.php
> Support {user}, other merge tags in content, attributes

- future/includes/rest/class-gv-rest-views-route.php
- includes/class-admin-welcome.php
- readme.txt
Resolves a problem where the global post was not properly set on Rest API calls, which made rest API calls break after #1836
> REST API Values properly being fetched on HTML mode.

- gravityview.php
- includes/class-admin-welcome.php
- includes/extensions/delete-entry/class-gravityview-field-delete-link.php
- readme.txt
* Fixed: PHP warning message that appeared when attempting to edit a View
> Release 1.18.1

- future/includes/class-gv-view.php
- gravityview.php
- includes/class-admin-welcome.php
- readme.txt
- tests/unit-tests/GravityView_Future_Test.php
- tests/unit-tests/GravityView_Shortcode_Test.php
- tests/unit-tests/GravityView_Widget_Search_Test.php
- translations.pot
* Fixed: Incorrect total entry count and hidden pagination when View contains an Entry Edit field
> Release 2.18.3

- future/includes/class-gv-shortcode-gvlogic.php
- readme.txt
- tests/unit-tests/GravityView_Future_Test.php
Resolves https://github.com/GravityKit/Dashboard-Views/issues/13
Does it break any tests, though?
> Allow `[gvlogic]` in admin

- .github/workflows/main.yml
- composer.lock
- gravityview.php
- includes/class-admin-welcome.php
- includes/class-gravityview-placeholder-template.php
- includes/fields/class-gravityview-field-gravityview_view.php
- readme.txt
- translations.pot
* Fixed: Using merge tags as values for search and start/end date override settings was not working in Views embedded as a field
* Fixed: Deprecation notice in PHP 8.2+
> Release 2.19.3

- readme.txt
- templates/fields/field-survey-html.php
This PR Closes #1906. 
There was no strict checking, so `false` was evaluated as `0` (`+ 1 = 1`).
> Show all empty stars on empty rating

- .circleci/config.yml
- composer.lock
- future/includes/class-gv-view.php
- gravityview.php
- includes/class-admin-welcome.php
- readme.txt
- translations.pot
This release enhances performance by optimizing caching and managing transients more effectively.
* Enhanced detection of duplicate queries, resulting in fewer cache records stored in the database.
* Updated [Foundation](https://www.gravitykit.com/foundation/) to version 1.2.10.
- Transients are no longer autoloaded.
> Release 2.20.2

- composer.json
- composer.lock
- includes/widgets/search-widget/class-search-widget.php
- readme.txt
- tests/unit-tests/GravityView_Widget_Search_Test.php
Adds support for part of #1966
This hasn't been tested. Needs further testing, unit tests!
> Allow exact-match searches

- includes/widgets/search-widget/class-search-widget.php
- Solves https://github.com/GravityKit/GravityView/issues/2113
- It's important for this PR https://github.com/GravityKit/Event-Field/pull/63
💾 [Build file](https://www.dropbox.com/scl/fi/7mxxs1iqaeihv3k22fc03/gravityview-2.27.1-6ab7c3904.zip?rlkey=3xhs7m622m0cga3lw9dqev2hn&dl=1) (6ab7c3904).
> Add placeholder in custom searchable fields in search widget

- includes/class-gravityview-change-entry-creator.php
- readme.txt
Should remove the fatal error on invalid typehint.
💾 [Build file](https://www.dropbox.com/scl/fi/erv4riamvjmaqan6bbw9e/gravityview-2.30-719de0ae3.zip?rlkey=5ui9r159bzkulf87ffe4nk15a&dl=1) (719de0ae3).
> Remove strict typehints

- gravityview.php
- includes/class-admin-welcome.php
- includes/class-gravityview-change-entry-creator.php
- includes/extensions/duplicate-entry/class-duplicate-entry.php
- readme.txt
This hotfix release resolves an issue with the Multiple Forms extension.
* Fatal error in the View editor when using joined data from multiple forms.
> Release 2.30.1

- future/lib/class-gamajo-template-loader.php
- tests/unit-tests/GravityView_Future_Test.php
- Implements https://github.com/GravityKit/GravityView/issues/2250
💾 [Build file](https://www.dropbox.com/scl/fi/i5hallx5wmje279qc8kf1/gravityview-2.33.2-bc353e265.zip?rlkey=lsiv0hrkud8y3ie1tfb5jstmb&dl=1) (bc353e265).
> Removes test code and Fixes test fail

- includes/widgets/search-widget/class-search-widget.php
- readme.txt
Fix searching for approval status fatal error if view has any joins ( Multiple Forms ).
💾 [Build file](https://www.dropbox.com/scl/fi/oqqkn7lu0s39g2644dvol/gravityview-2.33.2-f4c34ad27.zip?rlkey=922shc23n1hxd1hs6923guv71&dl=1) (f4c34ad27).
> Fix nullable left join fatal error #2253

- includes/class-admin-approve-entries.php
- readme.txt
- tests/unit-tests/GravityView_Entry_Approval_Test.php
- Implements https://github.com/GravityKit/GravityView/issues/2247
- Implements also https://github.com/GravityKit/GravityImport/issues/468
💾 [Build file](https://www.dropbox.com/scl/fi/qjo0tbc3wtgc6tbxbmtc1/gravityview-2.33.2-c5563ccd7.zip?rlkey=tj5lw2g4zsxf6ehb1jux4i88p&dl=1) (c5563ccd7).
> Adds entries without is_approved meta to the list of unapproved

- includes/extensions/entry-notes/class-gravityview-field-notes.php
- readme.txt
This implements #2266.
💾 [Build file](https://www.dropbox.com/scl/fi/9vtob5nto1ks9gnkr9ga6/gravityview-2.34-8dacc0fa2.zip?rlkey=69upf8c5m25xgxorsfn4k5bhr&dl=1) (8dacc0fa2).
> Fix script localization issue with Entry Notes assets

- includes/extensions/duplicate-entry/class-duplicate-entry.php
- readme.txt
Related to #2285
@Mwalek Please test
💾 [Build file](https://www.dropbox.com/scl/fi/xvrsqgx14ke80svyz0qou/gravityview-2.35-676c51c6b.zip?rlkey=9moubdq35v19b508lkgvwq1d6&dl=1) (676c51c6b).
> Adds hooks required to send notifications when duplicating entry

- includes/extensions/lightbox-entry/class-gravityview-lightbox-entry.php
- readme.txt
This implements #2291.
💾 [Build file](https://www.dropbox.com/scl/fi/olfh9dz016b46zkasfi4s/gravityview-2.35-110e6eb09.zip?rlkey=zmde6ofx8mlmcml3gdu305gav&dl=1) (110e6eb09).
> Fix Single Entry layout error in lightbox for joined forms

- future/includes/class-gv-settings-view.php
- includes/extensions/edit-entry/class-edit-entry-admin.php
- includes/extensions/edit-entry/class-edit-entry-locking.php
- readme.txt
This implements #2309.
💾 [Build file](https://www.dropbox.com/scl/fi/o7oc9q7pxfwotuc0jmjp1/gravityview-2.37-6f929ed6f.zip?rlkey=5bhdh44xho9933em447693f8f&dl=1) (6f929ed6f).
> Fix entry locking not working

- assets/js/fe-views.js
- readme.txt
This implements #2318.
Tested to work with GF 2.8.x and 2.9.6.
💾 [Build file](https://www.dropbox.com/scl/fi/8vi2o43hf5sugrjju3boe/gravityview-2.37-1e3cd3684.zip?rlkey=fbb8y62h4hu0ub8oaoxtmqkvx&dl=1) (1e3cd3684).
> Fix entry editing when forms have multiple pages
