GravityKit/GravityView

includes/class-admin-approve-entries.php
readme.txt

Also, refactor the meta update into a stand-alone method.

Add hooks after entry approval status is updated

---

includes/class-admin-approve-entries.php
readme.txt

PHP Warning:  Missing argument 2 for
`GravityView_Admin_ApproveEntries::update_approved_meta()`, called
in `wordpress/wp-content/plugins/gravityview/includes/class-admin-approve-entries.php` on line `352` and defined in
`wordpress/wp-content/plugins/gravityview/includes/class-admin-approve-entries.php` on line `369`

Fixed Approve Entries

---

includes/widgets/class-gravityview-widget.php

needed as the widget_id is protected.

Get the widget id

---

includes/class-data.php

display the view results order by RAND is not yet supported by
GFAPI::get_entries.

Random is not supported by GF

---

includes/extensions/edit-entry/class-edit-entry-render.php
readme.txt

- if we are not enqueueing css on error, then, no need to print scripts
- by using the &$field on line 1169 we were causing a duplication of
fields because of wrong array reference on the loop of line 1184
(together with the absence of the break; )
@link: http://uk.php.net/manual/en/control-structures.foreach.php -
read the warning message.

Duplicated fields on edit entry

---

includes/class-admin-welcome.php
includes/extensions/edit-entry/class-edit-entry-render.php
readme.txt

This is displaying errors when updating entries where the
username/email already exists

Remove the validation hook from User Registration Add-on

---

gravityview.php
includes/extensions/edit-entry/class-edit-entry-render.php
includes/extensions/edit-entry/class-edit-entry-user-registration.php
readme.txt
templates/fields/other_entries.php

Not possible to use “GravityView_frontend::get_view_entries()” as it
gets interferences from the search and other url arguments.

Refactor how the other_entries field is calculated

---

includes/widgets/search-widget/class-search-widget.php
readme.txt
templates/fields/date_created.php

Humans expect to search in their timezone, so before searching, we need
to convert the human time to the UTC time to fetch accurate results

Search date_created using UTC time not human time

---

gravityview.php
includes/class-gravityview-admin-bar.php
readme.txt

This was overwritten in
https://github.com/katzwebservices/GravityView/commit/687fc38dea8979f46c
e0abf2de4b5cde740d8abe by accident.

Restore admin bar improvements

---

includes/extensions/edit-entry/class-edit-entry-render.php

- save $form_after_validation with the validation results
- inject the results into the get_form() render function using the hook
gform_pre_render

Fix hidden validation messages

---

includes/class-template.php
includes/extensions/edit-entry/class-edit-entry-render.php

* Checking for loop_start prevents themes and plugins that pre-process
shortcodes from triggering the action before displaying. Like, ahem,
the Divi theme and WordPress SEO plugin
* Use `include()` instead of `include_once()` to fix pre-processing
issue
Fixes #488

Fix theme conflicts when themes have shortcode pre-processors

---

includes/class-api.php

Only generate the container HTML if there's a field label.
Fixes #490

Fix empty field container

---

includes/class-api.php
includes/class-common.php
includes/connector-functions.php
includes/fields/class-gravityview-field-date.php
includes/fields/class-gravityview-field-list.php
includes/fields/class-gravityview-field-quiz.php
includes/fields/class-gravityview-field-time.php
includes/helper-functions.php
includes/widgets/poll/templates/widget-poll.php
readme.txt
templates/fields/date.php
templates/fields/gquiz_grade.php
templates/fields/gquiz_is_pass.php
templates/fields/gquiz_percent.php
templates/fields/gquiz_score.php
templates/fields/list.php
templates/fields/quiz.php
tests/factory.php
tests/unit-tests/GravityView_API_Test.php
tests/unit-tests/helper-functions_Test.php

Quiz and Polls addons were breaking because they use
`gform_entry_field_value` filter, and the `$field` variable being
passed was an array, not `GF_Field`.

Fix Quiz and Poll fields

---

future/includes/class-gv-core.php
future/includes/class-gv-entry.php
future/includes/class-gv-plugin.php
future/includes/class-gv-view.php
gravityview.php
includes/class-api.php
includes/class-frontend-views.php
includes/class-oembed.php
includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php
tests/unit-tests/GravityView_Future_Test.php

More movement around, lots of tests, stubs, stub tests. Most parts of the plugin initialization.
We're pretty much ready to get rid of the old GravityView_Post_Types class altogether now. Of course we'll wait for hard deprecation, and removal milestones before doing this.

More plugin initialization

---

includes/class-frontend-views.php

Gravity PDF registers four query vars when registering their PDF endpoint. GravityView seems to pick up the 'lid' and 'action' parameters when checking if the current page is the home page. This causes it to skip the query modifications and displays the incorrect Gravity Form when an entry is edited on a front page. This commit includes these vars in the ignore list so GravityView can happily do its thing.
P.s may want to add a filter for the ignore list so others can easily add to it.

Resolves conflict with registered Gravity PDF query vars

---

gravityview.php
includes/admin/metaboxes/class-gravityview-admin-metaboxes.php
includes/class-admin-welcome.php
includes/class-api.php
includes/class-gravityview-merge-tags.php
includes/extensions/delete-entry/class-delete-entry.php
includes/extensions/edit-entry/partials/form-buttons.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-yoast-seo.php
languages/gravityview.pot
readme.txt

* Adds support for [DIY Layout](https://gravityview.co/extensions/diy-layout/), a layout for designers & developers to take full advantage of GravityView
* Tweak: Show "Embed Shortcode" helper if a View has widgets configured but not Fields
* Fixed: `tabindex` not properly set for Update/Cancel/Delete buttons in Edit Entry
* Fixed: Hide Yoast SEO Content & SEO Analysis functionality when editing a View

Version 1.22.4

---

future/includes/class-gv-view.php

Turn off post filters to prevent sanitize_post_field() from running
wp_check_invalid_utf8() and triggering "Array to string conversion"
notices.
@soulseekah You will likely want to make this look prettier

Prevent the magic method from filtering non-string values

---

.gitignore
.travis.yml
future/_mocks.php
future/includes/class-gv-license-handler.php
future/includes/class-gv-template-field.php
future/includes/class-gv-template-view-table.php
future/includes/class-gv-view.php
gravityview.php
includes/class-admin-welcome.php
includes/class-common.php
includes/class-frontend-views.php
languages/gravityview.pot
package.json
readme.txt
tests/unit-tests/GravityView_Future_Test.php

* Fixed: Slow front-end performance, affecting all layout types
* Fixed: Search not performing properly
* Fixed: "Enable sorting by column" option for Table layouts
* GravityView will require Gravity Forms 2.3 in the future; please make sure you're using the latest version of Gravity Forms!
__Developer Updates__
* Fixed: `GravityView_frontend::get_view_entries()` search generation
* Fixed: `gravityview_get_template_settings()` not returning settings
* Tweak: Cache View and Field magic getters into variables for less overhead.

Version 2.0.4

---

future/includes/class-gv-collection-view.php
future/includes/class-gv-template-entry.php
future/includes/class-gv-template-field.php
future/includes/class-gv-template-legacy-override.php
future/includes/class-gv-template-view.php
future/includes/class-gv-template.php
future/lib/class-gamajo-template-loader.php
includes/class-template.php

I forgot back-compat with older versions are why we hadn't been using `set_template_data()`…
That kind of thing is why we need to load our own version that we can rely on.
@soulseekah Can you review this? 
Fixes #1072

Namespace Gamajo template loader

---

future/includes/rest/class-gv-rest-route.php
future/includes/rest/class-gv-rest-views-route.php
tests/unit-tests/GravityView_REST_Test.php

The REST request didn't have a good way to handle when a View is embedded in a post or page. This affected the output of URLs, for example.
This allows defining the parent post/page via URL string.
Is this a decent way to do this, @soulseekah?

If ?post_id=123 is passed to REST request, set parent post/page

---

gravityview.php
includes/class-admin-welcome.php
includes/fields/class-gravityview-field-fileupload.php
readme.txt

Revert 9743f17ed50ec7b61f02a2e7805a44980eb97f1d
We can add this back in after making sure that it's working properly.
The reason we added it is so that it uses the GF-generated download URL with the hash. It's not a full URL, so I think pathinfo() isn't generating the extension properly, so it's not being recognized as an image.

Hotfix revert: images were turning into partial links

---

includes/class-api.php
templates/fields/field-entry_link-html.php
tests/unit-tests/GravityView_API_Test.php

Reproduces #1190, and also fixes #1190

Use $context when generating entry_link URL instead of old API

---

future/includes/class-gv-request.php
includes/extensions/edit-entry/class-edit-entry-render.php
templates/fields/field-edit_link-html.php

This bypasses the requirement for all forms in all joins to be satisfied when `gravityview_is_edit_entry` is true.
Fixes #1210

Fix #1210 - Accessing edit entry on joined Views

---

future/includes/class-gv-plugin.php
tests/unit-tests/GravityView_Future_Test.php

There were issues with the prior textdomain loading process::
- `load_plugin_textdomain()` was being passed an absolute path, so it wouldn't ever find anything
- `load_theme_textdomain()` didn't work; it would look for `/languages/fr_FR.mo`, which isn't plugin specific. Not really the correct usage.
- IIS paths weren't being fixed (backslashes)

Tweak textdomain loading

---

future/includes/class-gv-field.php
future/includes/class-gv-view.php
includes/class-frontend-views.php
tests/unit-tests/GravityView_Future_Test.php

This issue was likely introduced by the introduction of an empty `?sort` parameter in dec13f6e249361855047487369cedd97fdf2a1ee, as well as multisort.
The main issue is that `$skip_first` was being applied too aggressively; if the URL being passed only included one sort, like `?sort[20]=asc`, it was being skipped.
When a sort is provided but it's empty, `updateViewSorting()` returns an empty array, which breaks things.
@soulseekah Can you write some tests that play with this some more?
Fixes #1323

Fix sorting

---

includes/extensions/edit-entry/class-edit-entry-render.php

This PR fixes a conflict with GP Nested Forms where editing a child entry and then submitting a parent form in a GravityView Edit view resulted in an infinite loop. This PR resolves the issue by limiting the `filter_modify_form_fields()` method to only apply to the form that has been submitted rather than all forms that are passed through the `gform_pre_render` filter as Nested Forms calls this filter for each child form.

Fix recursion conflict with Nested Forms.

---

future/includes/class-gv-field.php
readme.txt
templates/fields/field-business_hours-csv.php
templates/fields/field-checkbox-csv.php
templates/fields/field-fileupload-csv.php
templates/fields/field-list-csv.php
tests/unit-tests/GravityView_Future_Test.php
tests/unit-tests/GravityView_REST_Test.php

I looked at HubSpot and Google Forms, and both these tools use semicolons to separate multiple items (like multiple checkboxes).

Change the CSV glue for multiple items

---

includes/extensions/edit-entry/class-edit-entry-render.php

Fix issues where functionality specific to the view's form is applied to forms loaded via a Nested Form field. This PR assumes that GravityView should not need to modify any form in a view other than the form for which the view was configured. This PR supersedes the previous #1353.
The specific issue we encountered occurred when a view was configured to only have certain fields editable. This caused only fields with matching IDs on the child form to be editable as well when adding/editing an entry via a child form in a Nested Form field on the view's form.

Fix Nested Forms compatibility issues.

---

future/includes/class-gv-template-field.php
gravityview.php
includes/class-admin-welcome.php
includes/class-api.php
includes/extensions/edit-entry/class-edit-entry-render.php
languages/gravityview.pot
readme.txt

Fixes potential fatal error we're still investigating. Add fallback when $entry isn't found.
See https://gravityview.slack.com/archives/CDSTQ9QQ0/p1582579758006300

Hotfix for get_slug() fatal error

---

includes/fields/class-gravityview-field-fileupload.php

I'm working on a plugin that offloads file uploads in Gravity Forms. The plugin adds meta data about each file, and uses that data later on to overwrite the file path to use the custom location. For multi-file uploads, this meta data is stored in arrays in the order the files were uploaded.
Integrating with Gravity View requires knowing the current file in the [loop of file paths](https://github.com/gravityview/GravityView/blob/master/includes/fields/class-gravityview-field-fileupload.php#L151). Without knowing the current index, it's difficult to know which file is being handled in cases of multi-file uploads. 
This pull request modifies the loop to make the `$index` available to the `gravityview/fields/fileupload/file_path` filter. The `$index` is added as a fourth argument to the …

Add index of the current file in the loop to the gravityview/fields/fileupload/file_path filter

---

future/includes/class-gv-view.php
readme.txt

This bug (#1496) affected everyone whose permalink structure contained a prefix (e.g., "/blog/")

Fix broken /csv endpoint on some hosts

---

.circleci/config.yml
tests/unit-tests/GravityView_Future_Test.php

- Limit tests to PHP 5.4, 5.6 and 7.4
- Use `~/` folder for non-plugin stuff like test dependencies, etc.
- Create new `shared` context
- Use `~/plugin` as the working directory where the repo is cloned

Updated CircleCI configuration

---

includes/extensions/edit-entry/class-edit-entry-render.php

This resolves a problem when the GravityView Edit Entry screen contains a File Upload field and a standard field, and the upload field has a file already uploaded but the standard field is empty. 
On submission with no changes, GravityView will successfully update the entry, but the UI will show all the fields as having a validation error.
This adjustment ensures the UI doesn't show any problems during submission for this use case.

Entry Editing: Unmark fields that failed validation, when processing 'At least one field must be filled out'

---

includes/widgets/search-widget/class-search-widget.php
readme.txt
tests/unit-tests/GravityView_Widget_Search_Test.php

Removing search filters with empty values would produce incorrect results when the operator is set to "is".

Fix search widget returning incorrect results when using "is" operator

---

includes/widgets/search-widget/class-search-widget.php

This should also fix sieve filters not working with Gravity Flow fields.
Fixes #1802

Fix sieve choices for address fields

---

future/includes/class-gv-wrappers.php
readme.txt

This is a big change, but I believe it's a Good Thing™. `gravityview()->views->get()` _should_ return all the Views available, not only if we're inside a CPT.
This modifies `get()` to parse the global `$post` object to also check for embedded shortcodes and blocks. The perfect lack of reliance on the global state is somewhat removed, but it's adding something we needed for GravityKit/Social-Sharing#28 and, I think, a lot of other page builder issues.
@mrcasual, please review this!

Parse the current global `$post` to detect Views

---

assets/js/admin-views.js
future/includes/class-gv-entry.php
includes/extensions/delete-entry/class-delete-entry-admin.php
includes/extensions/delete-entry/class-delete-entry.php
includes/extensions/delete-entry/class-gravityview-field-delete-link.php
readme.txt

This means that `delete_link` will now be properly returned in the `GravityView_Fields::get_all('gravityview');` response.

Make the Delete Link field an actual field

---

future/includes/class-gv-view.php
readme.txt
tests/unit-tests/GravityView_Field_Test.php
tests/unit-tests/GravityView_Future_Test.php
tests/unit-tests/GravityView_Joins_Test.php

This implements caching for repetitive DB queries to optimize speed, particularly for costly queries involving joins against the `wp_gf_entry` table containing millions of records.

Cache DB queries used to get all entries

---

includes/import-functions.php

With new Rich Text and Paragraph settings registered by the PDF for GravityView plugin, an export file can now contain new line characters in the `_gravityview_template_settings` meta. 
Adding the key to this patch so the info can be correctly imported.
Fixes https://github.com/GravityPDF/pdf-for-gravityview/issues/12

Fix unserialization issue for _gravityview_template_settings meta key

---

assets/js/admin-views.js
future/includes/class-gv-settings-plugin.php
includes/admin/field-types/type_textarea.php
includes/class-admin-views.php
includes/class-admin-welcome.php
includes/extensions/delete-entry/class-gravityview-field-delete-link.php
includes/extensions/edit-entry/class-edit-entry-admin.php
includes/fields/class-gravityview-field-custom.php
includes/fields/class-gravityview-field-edit-link.php
includes/fields/class-gravityview-field-entry-link.php
includes/fields/class-gravityview-field.php
readme.txt

- Resolves #1814
- Resolves #1946 
- Fixes #1947
------
This changes how we process toggles that show and hide values based on checkboxes.
We need to make sure that if a checkbox is checked that is supposed to show another field (like "Show Label"), the fields remain checked and the dependency fields remain visible.
Same for settings fields, like "Allow User Edit"—when checked, should show "Unapprove Entries After Edit".
Same with Maps:

Optimize and improve the View editor

---

assets/js/admin-views.js
future/includes/class-gv-form.php
includes/admin/metaboxes/views/view-configuration.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-advanced-post-creation.php
readme.txt

This PR addresses #1268 . 
It updates the connected Post if the entry is edited through GravityKit. **So not for gravity forms editing itself!**.
It also shows a notice if you provide an edit page and the APC add-on is active.

Support advanced post creation add on

---

composer.lock
future/includes/class-gv-settings-plugin.php
future/includes/class-gv-settings-view.php
future/includes/class-gv-view.php
includes/admin/metaboxes/views/view-settings.php
includes/class-cache.php
readme.txt
tests/unit-tests/GravityView_Field_Test.php
tests/unit-tests/GravityView_Future_Test.php
tests/unit-tests/GravityView_Joins_Test.php
tests/unit-tests/GravityView_Shortcode_Test.php
tests/unit-tests/GravityView_Widget_Search_Test.php

This adds a global (GravityKit > Settings > GravityView) and View setting to control caching. This also implements long-lived caching (https://docs.gravitykit.com/article/58-about-gravityview-caching) that we haven't had since... ages.
Ref: #1818.

Implement global and per-View caching of entries

---

includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-advanced-post-creation.php

On a new view without a connected form, this page showed a warning.

Only show notice when a form is set

---

future/includes/class-gv-core.php
future/includes/class-gv-view.php
includes/class-gravityview-admin-notices.php
includes/class-gravityview-compatibility.php
readme.txt

Ref: #1979
GV notices are reused but made non-dismissible on those two pages.

Display notice on All Views/New View pages when GF is not activated

---

includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-acf.php
readme.txt

This PR adresses #1812. 
It looks like a recursion is going on when trying to retrieve the meta fields for a post. It used the `get_field_objects()` method of ACF.  Apparently they are right when they say:
> The function is not very elegant and wastes a lot of PHP memory / SQL queries if you are not using all the fields / values
So I've replaced it with half the internal method, retrieving the meta keys for ACF only, and microcaching the result. 
This fixes the recursion for me, and I'm able to show the view when rendering `the_field('content');`.

Fix recursion in ACF fields with GravityView shortcodes

---

future/includes/class-gv-view.php
gravityview.php
includes/class-admin-welcome.php
includes/extensions/entry-notes/class-gravityview-field-notes.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-acf.php
readme.txt
tests/unit-tests/GravityView_20_Issues.php

This release fixes an issue with View caching and improves compatibility with the Advanced Custom Fields plugin.
- Disappearing pagination and incorrect entry count when View caching is enabled.
- Potential timeout issue when embedding GravityView shortcodes with Advanced Custom Fields plugin.
- PHP 8.1+ deprecation notice.

Release 2.20.1

---

future/includes/class-gv-entry-gravityforms.php
future/includes/class-gv-field-internal.php
future/includes/class-gv-form-gravityforms.php
future/includes/class-gv-template-field.php
includes/class-template.php
readme.txt

This PR adresses #1999 
The messages in that issue were fixed a long time ago; but there are a few that needed to be fixed.

remove 8.2 deprecations

---

includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-lifterlms.php

This should not be merged as-is…I just wanted to show @mrcasual my work toward resolving the fact that DataTables doesn't generate single entry links that work: https://github.com/GravityKit/GravityView/pull/1882#issuecomment-1970212456

[WIP] LifterLMS DataTables support

---

includes/widgets/search-widget/class-search-widget.php
tests/unit-tests/GravityView_Widget_Search_Test.php

This PR is part of #1966.
It allows for adding a plus `+` or minus `-` sign in front of words or exact matches eg: `-Pete` or `+"Pete Johnson"`. This will exclude or MUST include any entry that matches these values anywhere.

Add negative and positive search to global search.

---

includes/widgets/class-gravityview-widget-export-link.php
readme.txt

This PR addresses #2034 where the export link widget would cause a fatal error when searching on multiple words. 
The problem is that the space between the words is transformed into `%20`. And because the link is added to the `printf` function directly it reads that `%` as a placeholder. 
Fixed it by adding the link via a `%s` placeholder as well.

Fix export link widget by sanitizing link

---

includes/fields/class-gravityview-field-gravityview_view.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-perks-nested-forms.php

This PR addresses #1892. 
Basically everything asked for in that issue is solved. But to reference the parent in the merge tags you need to use: `{Parent:<field>}` So `{Parent:1.2}` or `{Parent:entry_id}` or `{Parent:form_id}`.
And to be able to connect in the view search field you need to search for  the key `gpnf_entry_parent` or `gpnf_entry_parent_form`.
💾 [Build file](https://www.dropbox.com/scl/fi/jgdhs9mnmju6uxqaji8o5/gravityview-2.22-7f95583e8.zip?rlkey=svggtxibwx92eulbdzg045bgs&dl=1) (7f95583e8).

Support for nested forms entry meta

---

includes/widgets/search-widget/class-search-widget.php
includes/widgets/search-widget/templates/search-field-input_text.php
readme.txt
tests/unit-tests/GravityView_Widget_Search_Test.php

This PR Addresses #2063 
The check only looked for product fields, but did not take into account it could just be searching for a text. When using a Range, the filters are set to `is_numeric`. This is now added to the check to be sure it still searches on text too.
Tests added to prevent future regression.
💾 [Build file](https://www.dropbox.com/scl/fi/9i1s1ocvommim4tkhcy40/gravityview-2.23-6bfe2cd5d.zip?rlkey=ueaiujhl48craxg5qvrxvbpo7&dl=1) (6bfe2cd5d).

Fix product field search with text

---

includes/widgets/class-gravityview-widget-export-link.php
includes/widgets/search-widget/class-search-widget.php
readme.txt

This PR Addresses #2053. The date range (and global search) is prefixed with `gv_` instead of `filter_`. These values are now also extracted and passed along to the CSV download url.
💾 [Build file](https://www.dropbox.com/scl/fi/ap53hk13mu1he3e7pnmrb/gravityview-2.23-a288e7e63.zip?rlkey=10fslr0z107w9qxuw7b6y3f47&dl=1) (a288e7e63).

Use date range filter on View widget

---

includes/class-gravityview-notifications.php
readme.txt

This fixes #2060 where merge tags for fields populated by Populate Anything return values rather than labels.
💾 [Build file](https://www.dropbox.com/scl/fi/upe3grhmccamhy49phjle/gravityview-2.23-c0b265973.zip?rlkey=yye9aer0tki7ibx06ttuyb0mc&dl=1) (c0b265973).

Trigger "gform_pre_render" before sending notifications

---

includes/class-gravityview-merge-tags.php
readme.txt

This fixes #2102 and supports various [time format characters](https://www.php.net/manual/en/datetime.format.php), including escaped values and colons such as `\a\t\ H\:i\:s` ([per our guide](https://docs.gravitykit.com/article/331-date-created-merge-tag)).
💾 [Build file](https://www.dropbox.com/scl/fi/mokngjdlvsm116ygdcpb6/gravityview-2.26-07edb8b83.zip?rlkey=jp8uodmb3cqyc5oisyc27aw1i&dl=1) (07edb8b83).

Use local timezone when formatting Time fields

---

assets/js/admin-views.js
gravityview.php
includes/class-admin-views.php
includes/class-admin-welcome.php
includes/class-gravityview-merge-tags.php
includes/fields/class-gravityview-field-approval.php
includes/plugin-and-theme-hooks/class-gravityview-object-placeholder.php
includes/widgets/search-widget/templates/search-field-select.php
readme.txt

This update resolves several issues related to the Multiple Forms extension, fixes the recently introduced `:format` merge tag modifier to return the Time field value in the local timezone, and adds a new filter to control which fields are added by default when creating a new View.
* Time zone selection in the Search Bar did not persist after searching a View, causing it to reset upon page refresh.
* Fields added to the View could not be configured and would disappear after saving the View when Multiple Forms was enabled.
* Fatal error occurred on the Edit Entry screen when Multiple Forms was enabled.
* The `:format` merge tag modifier on the Time field returned a UTC-adjusted time value.
* Added `gk/gravityview/view/configuration/multiple-entries/initialize-with-all-form-fields` filter …

Release 2.27

---

assets/js/admin-views.js
gravityview.php
includes/class-admin-welcome.php
readme.txt

This release fixes an issue with adding fields in the View editor's Edit Entry layout when the Multiple Forms extension is enabled.
* Fields added to the Edit Entry layout in the View editor could not be configured and would disappear after saving the View when Multiple Forms was enabled.
💾 [Build file](https://www.dropbox.com/scl/fi/6d53n1y41ew4s0okmf2o2/gravityview-2.27.1-2792e8566.zip?rlkey=zxgce968haa7ltomdgy1pkujf&dl=1) (2792e8566).

Release 2.27.1

---

includes/extensions/edit-entry/class-edit-entry-render.php

- This solves https://github.com/GravityKit/GravityView/issues/2086
- The edit entry validation for max files works but after the user clicks edit entry.
- The issue here is the files are uploaded to the uploads folder before they are validated
- Gravity forms already has a good ajax validation for this part but we have a filter that removes that validation in GravityView 
`add_filter( 'gform_plupload_settings', array( $this, 'modify_fileupload_settings' ), 10, 3 );`
- It says that it was added because our custom validation already handles that so we don't have a conflict ( I tried to find that conflict but couldn't)
- So we can leave it as it is and we would have ajax validation (gf validation) and also a custom validation after the user clicks update (Our validation)
- Or we can keep …

Removes the filter that removed gf max files validation

---

includes/widgets/search-widget/templates/search-field-date_range.php

- FIxes https://github.com/GravityKit/GravityView/issues/2115
- You can test it with this PR https://github.com/GravityKit/Event-Field/pull/63
💾 [Build file](https://www.dropbox.com/scl/fi/udg5bubiztk0qgoqw7wcu/gravityview-2.27.1-fd80f29b3.zip?rlkey=82pxrbgyelr7wh7999joj2av7&dl=1) (fd80f29b3).

Check if value has start and end dates

---

future/includes/class-gv-template-view-table.php
future/includes/class-gv-view.php
includes/class-frontend-views.php
readme.txt

This fixes #2121.
[GravityMigrate data](https://github.com/user-attachments/files/15906747/gk-migrate-neeast.com-2024-06-19-1718840620.zip).
💾 [Build file](null) (ceb6104ec).

Implement proper sorting for the Name field

---

future/includes/class-gv-view.php
readme.txt

This implements #1759.
To test, use this filter:
```
add_filter( 'gk/gravityview/view/entries/query/sorting-parameters', function ( $params ) {
foreach ( $params as &$field ) {
$field['is_numeric'] = true;
}
return $params;
} );
```
[GravityMigrate data](https://github.com/user-attachments/files/16765603/gk-migrate-debug.try.gravitykit.com-2024-08-26-1724694417.zip).
💾 [Build file](https://www.dropbox.com/scl/fi/5ik2t3mr6pk8lx4m91wg5/gravityview-2.27.1-81f6fa655.zip?rlkey=35eq2s9hyesjukmd0lsrvrp4n&dl=1) (81f6fa655).

Add filter to control sorting in View entries query

---

includes/class-common.php
includes/class-gravityview-merge-tags.php
includes/fields/class-gravityview-field-date.php
readme.txt
tests/unit-tests/GVCommon_Common_Test.php

- FIxes https://github.com/GravityKit/GravityView/issues/1990
- I had to edit the `GravityView_Field_Date` class because it was overriding the human modifier by running the function again without the new arguments and i couldn't remove the filter `gravityview/merge_tags/modifiers/value` as it was happening after the human modifier function.
💾 [Build file](https://www.dropbox.com/scl/fi/55s0yfg7q7x5h663r349q/gravityview-2.28.0-cb02ebddc.zip?rlkey=nmffl5isaq265aj4fzxsel67g&dl=1) (cb02ebddc).

Add human modifier for date and time fields

---

includes/class-api.php
readme.txt

- Fixes https://github.com/GravityKit/GravityView/issues/2090
- The wpautop function breaks the scripts from Datatables, So I disabled them for all gv views fields in this area
💾 [Build file](https://www.dropbox.com/scl/fi/iwvs16imny6ao0sp0apf2/gravityview-2.28.0-03f043413.zip?rlkey=a1k6wa56fxkovhjvoicpxebw3&dl=1) (03f043413).

Fix embedded views in other fields

---

assets/js/admin-views.js
assets/js/fe-views.js
future/includes/class-gv-plugin.php
includes/admin/class.render.settings.php
includes/extensions/delete-entry/class-delete-entry.php
includes/extensions/duplicate-entry/class-duplicate-entry.php
includes/extensions/lightbox-entry/class-gravityview-lightbox-entry-request.php
includes/extensions/lightbox-entry/class-gravityview-lightbox-entry.php
includes/extensions/lightbox/fancybox/class-gravityview-lightbox-provider-fancybox.php
includes/fields/class-gravityview-field-edit-link.php
includes/fields/class-gravityview-field-entry-link.php
includes/fields/class-gravityview-field.php
readme.txt
templates/fields/field-edit_link-html.php

_(work was initially done in https://github.com/GravityKit/GravityView/pull/2055)_
1. Add a "Link to Single Entry" field
2. Open field settings
3. Check the "Open in a lightbox?" checkbox
4. Save the View
* How do we handle updating data? When closing the lightbox, if an entry has been edited, outdated values may be shown.
* Will Inline Edit work inside this? 🤯
- If enabled, should we disable Inline Edit?
💾 [Build file](https://www.dropbox.com/scl/fi/fdp5fvj9zm2usa8hmysik/gravityview-2.28.0-49301e324.zip?rlkey=xdty6oork78qputtuqm57bllq&dl=1) (49301e324).

Single entry in lightbox

---

tests/unit-tests/GVCommon_Common_Test.php

- Fixes  https://github.com/GravityKit/GravityView/issues/2152
- Fixed tests that might fail because of timezones
- The issue was that i was using `GFCommon::get_local_timestamp` to convert the timestamp to the local one according to current site timezone
- Then i was comparing it using human_time_diff function which uses `time()` as the second argument by default which is just the regular timestamp not adjusted for the current site timezone
💾 [Build file](https://www.dropbox.com/scl/fi/nda4akon14625rfjeqxra/gravityview-2.28.0-7ad65298c.zip?rlkey=e0pyr0vzeu9q30v9sq1bkwwuw&dl=1) (7ad65298c).

Fix failing tests

---

includes/class-admin-welcome.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-lifterlms.php
readme.txt

Ref: https://wordpress.org/support/topic/lifterlms-fatal-error/
To reproduce the original issue: activate GravityView (`develop` branch) followed by LifterLMS.
After the fix:
I did not test the actual functionality, but all settings work.
💾 [Build file](https://www.dropbox.com/scl/fi/s8lds3vs7lswre571jb2d/gravityview-2.31-43a55ba24.zip?rlkey=o4folrfrvntonowdozee2izme&dl=1) (43a55ba24).

Fix fatal error when activating LifterLMS

---

includes/admin/class.render.settings.php
includes/class-admin.php
readme.txt

This PR moves over the field options for `lightbox` and `new_window`, so these can be disabled in some instances.
It introduces a new (fully typed ;-) ) filter hook `gk/gravityview/template/options`. This filter is applied after the existing ones, and is for more general purposes. This is the reason the attributes are limited to: the options, field type (widget | field), template ID, context, whether it is grouped, and the form ID. There are no specifics about the field itself, or its type. We already have hooks for that.
This PR also resolves an old TODO that sorts the options via this hook, and it has a bit of auto formatting.

Allow field option filtering on lightbox and new_window settings

---

assets/js/admin-grid.js
readme.txt

This PR adds a `gravityview/row-added` event when a new row is added to a Widget/Field area. We need this event in order to make it compatible with Multiple Forms. https://github.com/GravityKit/Multiple-Forms/pull/108
💾 [Build file](https://www.dropbox.com/scl/fi/8lbpmsunhwx9y9cnrvz32/gravityview-2.31.1-c72774b88.zip?rlkey=rypy2mjqxd3tyk9jk9i89vief&dl=1) (c72774b88).

Add gravityview/row-added JS-event

---

future/includes/class-gv-view.php
readme.txt

Adds a filter for join conditions. Most immediately, this is required for https://github.com/GravityKit/Multiple-Forms/pull/105.
💾 [Build file](https://www.dropbox.com/scl/fi/rgwjagesqw34naf4rkgw6/gravityview-2.31.1-753893103.zip?rlkey=qphdqt1tkm7nd0pmiev3xx8bs&dl=1) (753893103).

Filter join conditions #2198

---

includes/extensions/edit-entry/class-edit-entry-render.php

- Implements https://github.com/GravityKit/GravityView/issues/2208
- The main issue was gform_basic was loaded before gform_admin_icons
- I tried to reverse the order of the enqueue but that can't be done as gform_basic is not loaded with enqueue and it caused some style issues
- So i added an override style using gform_theme which only loads when 2.5 style theme is chosen and it's only loaded also if gf is 2.9 or more
💾 [Build file](https://www.dropbox.com/scl/fi/wmntwhiitk4zqhuwds804/gravityview-2.31.1-cf9276ee2.zip?rlkey=ezexazo9lscptibi4x342kl5a&dl=1) (cf9276ee2).

Fixes upload buttons not showing up

---

templates/deprecated/fields/post_image.php
templates/fields/field-post_image-html.php
tests/unit-tests/GravityView_Edit_Entry_Test.php
tests/unit-tests/GravityView_Future_Test.php

Gravity Forms added a caching mechanism, and since we test multiple states in the same test, instead of separate tests with a data provider it hits this cache. This PR clears that cache for every `_emulate_render` call.
Also removed any lingering `GFFormsModel::is_html5_enabled` calls as that is deprecated; and has been returning `true` for a while now. 
💾 [Build file](https://www.dropbox.com/scl/fi/5kltisoxfdq8u44jdqkuu/gravityview-2.31.1-290e52fb9.zip?rlkey=jyk6b6dy8x3iyej7qcjpb8q26&dl=1) (290e52fb9).

Fix unit tests on GravityForms 2.9

---

future/includes/class-gv-permalinks.php
future/includes/class-gv-shortcode-gravityview.php
readme.txt

This PR addresses #2207 
When using shortcodes, its hard to determine the correct View for its settings. This PR records the View when the shortcode is being rendered. Based on that value we can now determine the settings correctly. After the shortcode is rendered it forgets the View.
For testing, also test multiple Views on the same page with different Entry slug settings.
💾 [Build file](https://www.dropbox.com/scl/fi/k5dfjawy100618cixj3th/gravityview-2.32-6dcf3f8c1.zip?rlkey=3bpohg1sty1awb594i5yfsdo7&dl=1) (6dcf3f8c1).

Fix custom Entry slug on embedded Views (#2207)

---

includes/class-api.php
includes/class-frontend-views.php

This PR addresses some minor things. I didn't want to push to `develop` as we are about to release. But if this is agreeable, please merge. 
There is a fix for the `is_approved` condition. That currently uses a `LIKE` which is the default comparator. This is somewhat slow compared to `=`, and it is prone to future errors where a status of `11` would become a thing for example as that would then also match. In addition, multiple forms already uses `=` for the joined forms. It's just the original that doesn't. 
Furthermore I updated the calculation of the field ID, as the can cause duplicates on the page when multiple forms are joined. Fields from other forms will still have the original form ID in the `id` attribute, which can cause duplicates if another field with that ID exists. So I …

Miscellaneous fixes

---

future/includes/class-gv-template-view-table.php
readme.txt

This implements #2237.
💾 [Build file](https://www.dropbox.com/scl/fi/tpfx99xvli96oc1u0e74w/gravityview-2.32-420bd45dc.zip?rlkey=vj7ziapgx8fspkrqb7em2s4m9&dl=1) (420bd45dc).

Fix empty column headers in Multiple Forms mobile view #2237

---

gravityview.php
includes/class-admin-welcome.php
includes/extensions/entry-notes/class-gravityview-field-notes.php
readme.txt

This update fixes an issue with entry notes being displayed.
* Entry notes being displayed.
💾 [Build file](https://www.dropbox.com/scl/fi/e1nufgxdgi3m9dmdfezua/gravityview-2.33.1-d00ac1269.zip?rlkey=poxjxe8z6htcyy7289y3j1qys&dl=1) (d00ac1269).

Release 2.33.1

---

includes/class-gravityview-entry-approval.php
readme.txt

- Implements https://github.com/GravityKit/GravityView/issues/2229
- Adds approval status to export entries conditional logic
💾 [Build file](null) (bf6b976d4).

Adds approval status to export entries conditional logic

---

includes/class-gravityview-merge-tags.php
includes/fields/class-gravityview-field-date.php
readme.txt

This implements #2257.
💾 [Build file](https://www.dropbox.com/scl/fi/dq57dduahqi1vpytsin8o/gravityview-2.33.2-66d86036f.zip?rlkey=y18o4sqkaw972uafe27jppnrm&dl=1) (66d86036f).

Do not apply site's timezone offset to Date fields

---

future/lib/class-gamajo-template-loader.php
gravityview.php
includes/class-admin-approve-entries.php
includes/class-admin-welcome.php
includes/class-gravityview-entry-approval.php
includes/class-gravityview-merge-tags.php
includes/fields/class-gravityview-field-date.php
includes/presets/layout-builder/class-gravityview-layout-builder.php
includes/widgets/search-widget/class-search-widget.php
readme.txt
tests/unit-tests/GravityView_Entry_Approval_Test.php
tests/unit-tests/GravityView_Future_Test.php

This release introduces the [Layout Builder](https://www.gravitykit.com/announcing-gravityview-2-4-all-new-layout-builder/) that allows creating custom layouts with rows and columns directly in the View editor, adds support for exporting entries by Approval Status, and includes various fixes and improvements.
* New Layout Builder View type for creating custom layouts with single or multi-column configurations and adjustable widths.
* Support for using entry Approval Status in conditional logic rules on the Gravity Forms Export Entries page.
* Entries added via the Gravity Forms API or while GravityView is inactive can now be filtered using the "Unapproved" status on the Entries page.
* Fatal error when searching entries by Approval Status in Views joined with another form using the …

Release 2.34

---

includes/extensions/delete-entry/class-delete-entry.php
readme.txt

This implements #2261.
💾 [Build file](https://www.dropbox.com/scl/fi/ha9ai9bgydh3k5s1wj9a8/gravityview-2.34-699597726.zip?rlkey=k3arkk857ra0fv67gqy0rxiwq&dl=1) (699597726).

Allow main network site users to delete own entries on subsites

---

gravityview.php
includes/class-admin-welcome.php
includes/class-cache.php
includes/class-gravityview-merge-tags.php
includes/extensions/delete-entry/class-delete-entry.php
includes/extensions/edit-entry/class-edit-entry-locking.php
includes/extensions/edit-entry/class-edit-entry.php
includes/extensions/entry-notes/class-gravityview-field-notes.php
includes/extensions/lightbox-entry/class-gravityview-lightbox-entry.php
includes/fields/class-gravityview-field-date.php
readme.txt
templates/views/gravityview-layout-builder.php
tests/unit-tests/GravityView_Merge_Tags_Test.php

This update resolves multiple issues, including problems with search bar visibility in Layout Builder, entry management in multisite environments, and non-functional entry locking and notes, among others.
* The Search Bar would not always be visible in Views using the Layout Builder.
* Users belonging to the main network site in a multisite environment couldn’t delete their own entries on subsites.
* Entry locking not working.
* JavaScript error preventing entry notes from being added when using the Twenty Twenty-Two theme or newer.
* Using a comma in the `:format` merge tag modifier with Date fields caused partial results to be returned.
* Added `gk/gravityview/edit-entry/renderer/enqueue-entry-lock-assets` filter to override whether to load the entry lock UI assets.
* Added …

Release 2.34.1

---

future/includes/class-gv-plugin.php
readme.txt

This addresses #2268.
💾 [Build file](https://www.dropbox.com/scl/fi/5y76e4wyxev43i0wttzv0/gravityview-2.34.1-f1187ffdd.zip?rlkey=8qre5u1hkrsb87v8tyew1ppkf&dl=1) (f1187ffdd).

Fix "function _load_textdomain_just_in_time was called incorrectly" notice

---

future/includes/class-gv-plugin.php
gravityview.php
includes/class-admin-welcome.php
readme.txt
templates/views/gravityview-layout-builder.php

This release fixes a PHP notice in WordPress 6.7+ and a display issue in Views using the Layout Builder template.
* `function _load_textdomain_just_in_time was called incorrectly` PHP notice in WordPress 6.7 or newer.
* Display issue caused by a malformed `div` tag in the Layout Builder View template.

Release 2.34.2

---

includes/class-admin-approve-entries.php
readme.txt

This implements #2273.
[Test site](https://gv-pr-2281.try.gravitykit.com/wp-admin/admin.php?page=gf_entries&id=2) (see InstaWP for credentials).
💾 [Build file](https://www.dropbox.com/scl/fi/rt1tgjcfrsucn7q5nzhob/gravityview-2.34.2-cc95f7f9b.zip?rlkey=vr3buygjrmmqv897ilxx2qdmr&dl=1) (cc95f7f9b).

Exclude partial entries from the Unapproved filter

---

includes/class-admin-views.php
includes/class-common.php
readme.txt

- Implements https://github.com/GravityKit/GravityView/issues/2262
- Orders the forms alphabetically
- Fixed `get_forms` as there was an issue with using wp_list_sort when it came to strings as it was ordering them wrong
💾 [Build file](https://www.dropbox.com/scl/fi/xwxri01502ee03636vi1w/gravityview-2.35-80df57f24.zip?rlkey=pwe8hzsotfvcaoq0uqnpbrloh&dl=1) (80df57f24).

Order forms alphabetically in the dropdown on the All Views page

---

future/includes/class-gv-entry-multi.php
includes/class-gravityview-admin-bar.php
readme.txt

When using Multiple Forms (or anything that returns a `Multi_Entry` the admin-bar tries to get the `id` and `form_id` via the ArrayAccess methods; however, that doesn't work for the `Multi_Entry`. This PR addresses that by getting the entry as an array first.
`Multi_Entry` also did not have a valid `ID` which this PR also addresses.

Fix Edit Entry link in admin bar for multi entries

---

assets/js/fe-views.js
future/includes/class-gv-settings-view.php
future/includes/gutenberg/package-lock.json
gravityview.php
includes/class-admin-welcome.php
includes/class-frontend-views.php
includes/extensions/edit-entry/class-edit-entry-admin.php
includes/extensions/edit-entry/class-edit-entry-locking.php
includes/extensions/edit-entry/class-edit-entry-render.php
includes/fields/class-gravityview-field-gravityview_view.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-chainedselects.php
includes/widgets/class-gravityview-widget-page-links.php
readme.txt
templates/views/gravityview-layout-builder.php

This release adds a new setting for Edit Entry locking and fixes issues with multi-page form entry editing, shortcode rendering inside the Layout Builder template, entry locking, and more.
* View editor setting to control how frequently requests to take control of a locked entry are checked when Edit Locking is enabled.
* Navigation between pages in multi-page forms was broken when editing entries.
* GravityView View field in the Single Entry layout may not display results when accessed from a paginated View.
* `[gv_entry_link]` shortcode was not rendering inside the Custom Content field when using the Layout Builder template.
* Fatal error when a Chained Selects Add-On search field was added to the Search Bar, then removed from the connected form.
* Entry locking not working in certain …

Release 2.38

---

composer.lock
composer_public.json
gravityview.php
includes/class-admin-welcome.php
readme.txt
translations.pot

This hotfix resolves a fatal error that occurred when updating the plugin from version 2.38 or earlier.
* Fatal error when updating the plugin from version 2.38 or earlier.
* [Foundation](https://www.gravitykit.com/foundation/) to version 1.2.25.

Release 2.39.1

---

includes/fields/class-gravityview-field-fileupload.php

Resolve a bug where filenames with spaces are not correctly encoded when run through `$field->get_download_url()`, causing the filename and link to break.
**BEFORE**
**AFTER**
By adjusting the space character encoding until after the URL is secured the file can now be viewed and downloaded.
Note: Gravity Forms auto-removes spaces from filenames when files are uploaded via traditional means. To replicate this bug you need to use manually added the file to the correct directory and use `GFAPI::create_entry()`.

Adjust order of encoded space in file upload field

---

future/includes/gutenberg/blocks/entry-field/block.php
future/includes/gutenberg/blocks/entry-link/block.php
future/includes/gutenberg/blocks/entry/block.php
future/includes/gutenberg/blocks/view-details/block.php
future/includes/gutenberg/blocks/view/block.php
includes/class-common.php
includes/wordpress-widgets/class-gravityview-recent-entries-widget.php
includes/wordpress-widgets/class-gravityview-search-wp-widget.php
readme.txt

When "Preview as shortcode" was enabled in the View editor, some blocks would render improperly on the frontend, showing JSON instead of block content.
Resolves #2357 
💾 [Build file](https://www.dropbox.com/scl/fi/nmr9jf4jugia6nfurwt7x/gravityview-2.40-4114a353c.zip?rlkey=mh15nrjakm2cyppbgah5lwdq0&dl=1) (4114a353c).

Prevent JSON from appearing when rendering block

---

includes/load-plugin-and-theme-hooks.php
includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-buddypress.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-learndash.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-ultimate-member.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-woocommerce.php
includes/plugin-and-theme-hooks/trait-gravityview-permalink-override.php
readme.txt

This fixes issues where single entry and edit entry links weren't properly rendering in LearnDash, BuddyPress, BuddyBoss, WooCommerce Account Tabs, and Ultimate Member.
Resolves #1931 
Before: 
- Entry links may or may not work, with format of example.com/my-account/page/entry/123/
- Edit Entry links did not work, with format of `example.com/my-account/page/entry/123/?edit=dasdsad&gvid=567`
After:
- Entry links work, with format of `example.com/my-account/page/entry/123/?entry=123`
- Edit Entry work, with format of `example.com/my-account/page/entry/123/?edit=dasdsad&gvid=567&entry=123`
Note that `entry=123` is appended.
@Mwalek to test, 
- Install and activate WooCommerce
- Set up account page landing page (`my-account` is default, I believe)
- Install WooCommerce Account Pages (contact …

Add a common framework for supporting third-party endpoints

---

gravityview.php
includes/fields/class-gravityview-field-address.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-image-hopper.php
package-lock.json
readme.txt
tests/unit-tests/GV/Search/Fields/Search_Field_Gravity_Forms_Test.php

This hotfix resolves a display issue introduced in 2.42 affecting address subfields in the Search Bar widget, and fixes a fatal error related to the Image Hopper Post Image field.
* Address field subfields (State/Province, City, etc.) were not displaying in the Search Bar widget after the 2.42 update.
* Fatal error when editing an entry containing an Image Hopper Post Image field.

Release 2.42.2

---

.circleci/config.yml
gravityview.php
includes/admin/class.field.type.php
includes/class-admin-views.php
includes/class-common.php
includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-gravity-forms-signature.php
readme.txt
templates/entries/list.php
templates/fields/field-time-html.php
tests/E2E/tests/edit-entry/file-size-limit.spec.js
tests/E2E/tests/edit-entry/max-file-deletion-rollback.spec.js
tests/unit-tests/GravityView_Field_Test.php

This update fixes several issues, including DIY Layout container tag selection, incorrect Time field value display, and various PHP warnings and deprecation messages.
* Time field values displaying incorrectly when the server and WordPress are set to different timezones.
* Choosing "None" as the container tag in DIY Layout not being saved and reverting to "DIV".
* Inline editing automatically enabled on Single Entry pages in List Views when using GravityEdit.
* "Undefined array key" PHP warning that could occur when using the Gravity Forms Signature Add-On.
* Various PHP warnings and deprecated notices.
💾 [Build file](https://www.dropbox.com/scl/fi/84o7421ldu712gmibd42s/gravityview-2.43.1-3f244836f.zip?rlkey=jijbuusa8gyiumim68frymvwa&dl=1) (3f244836f).

Release 2.43.1

---

.gitignore
includes/fields/class-gravityview-field-checkbox.php
readme.txt
templates/fields/field-checkbox-html.php

Introduces a new "Display Format" setting for checkbox fields allowing users to choose between bulleted lists (default) and comma-separated values display without requiring custom code.
Features:
• New radio setting in field configuration: "Bulleted list" vs "CSV"
• Respects existing choice_display setting (label/value)
• Only available for parent checkbox fields (not individual inputs)
• Includes developer filter for custom separators
• Full backward compatibility maintained
Implementation:
• Added display_format field setting to GravityView_Field_Checkbox class
• Created reusable static helper method format_checkbox_csv() with early returns
• Updated field-checkbox-html.php template with clean conditional logic
• Added gravityview/field/checkbox/csv_separator filter for customization …

Add field setting to display checkbox fields as a comma-separated list

---

future/includes/rest/class-gv-rest-views-route.php

I don't understand any scenario where you would want to have an error state when there are no entries. It seems like looping through an entry set of zero and returning the correct headers is the expected state. So I think that this code was a bug to begin with.
I've looked throughout our codebases and we don't have any expectation of the `gravityview-no-entries` error code being returned. Also, I searched for the string "No Entries found." and found no instances of that as well.
This seems to be the only place in our code where this response is used. I believe it is safe to remove it.
The only hesistance I have with this fix is that it doesn't automatically generate CSV headers when there are no entries; [those header columns are generated during the …

Always return expected response format from REST API, even when a View has no entries

---

.gitattributes
.gitignore
composer.lock
future/includes/class-gv-collection-field.php
future/includes/class-gv-shortcode.php
future/includes/class-gv-template-view-table.php
gravityview.php
includes/admin/class.render.settings.php
includes/admin/metaboxes/views/gravityview-content.php
includes/class-api.php
includes/class-frontend-views.php
includes/class-gravityview-entry-approval.php
includes/class-template.php
includes/extensions/delete-entry/class-delete-entry.php
includes/extensions/duplicate-entry/class-duplicate-entry.php
includes/extensions/edit-entry/class-edit-entry-render.php
includes/extensions/lightbox-entry/class-gravityview-lightbox-entry.php
includes/fields/class-gravityview-field-list.php
includes/helper-functions.php
includes/widgets/search-widget/templates/search-field-link.php
readme.txt
templates/deprecated/fields/email.php
templates/deprecated/fields/post_image.php
templates/deprecated/list-body.php
templates/fields/field-email-html.php
templates/fields/field-post_image-html.php
templates/fields/field-sequence.php
tests/unit-tests/GravityView_Edit_Entry_Test.php
tests/unit-tests/helper-functions_Test.php
translations.pot

This release adds the ability to output column values from multi-column List fields using merge tag modifiers, notifies admins when users access pages with misconfigured shortcode secrets, and fixes issues with Checkbox field settings, Result Number sequencing, and a potential PHP error with Address fields.
* Support for the List field merge tag modifier (e.g., `{List:1:2:text}`), enabling output of column values as an HTML list (default) or as a comma-separated string.
* An admin notice is displayed when a GravityView shortcode’s required `secret` attribute is missing or invalid.
* Display issue with Checkbox field settings in the View editor where related "Link to single entry" options were not grouped together.
* Result Number field now respects the "First Number in the Sequence" …

Release 2.46
